name: Kong
favicon: null
layout_spectrum: 0.43472390598617494
typography_spectrum: 0.3152828433085233
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5657176768872887
  lightness: 0.7360841436311603
  saturation: 0.749867839505896
  rhythmicContrast: 0.22646347084082663
purpose: []
