name: Kong
favicon: null
layout_spectrum: 1
typography_spectrum: 0.3152828433085233
title: Photos of Hong Kong
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0c0304'
    - '#f9f8f6'
    - '#5f2620'
    - '#cac1b8'
    - '#d37c27'
  brandStrength: 0
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
